#!/usr/bin/env bash

run_test () {
    uv run pytest omnisound/test/$1.py::$2 -W ignore::UserWarning -W ignore::DeprecationWarning
}

run_test_file () {
    uv run pytest omnisound/test/$1.py -W ignore::UserWarning -W ignore::DeprecationWarning
}

run_tests () {
    uv run pytest omnisound/test/ -W ignore::UserWarning -W ignore::DeprecationWarning --code-highlight=yes --no-header
}